### ISSUE TITLE
合并时报错：当前系统未安装ffmpeg，请在终端中执行：“brew install ffmpeg” 进行安装~

### ISSUE THREAD

**Issue by springHyc** [lecepin/tss-merge-to-mkv#11]
第一次提示我没有安装ffmpeg时，我按照提示安装好了，再合并，还是报没有安装ffmpeg

**Comment by dorameonsu** [comment]
> 第一次提示我没有安装ffmpeg时，我按照提示安装好了，再合并，还是报没有安装ffmpeg
ls -l | sort -V -k 9,9 | awk '/^-/{print "file \"" $9 "\""}' | sed "s/\"/'/g" | grep -v "file_list.txt"  > file_list.txt

ffmpeg -f concat -i file_list.txt -c copy output.mp4

在终端 用cd到文件夹哪里 然后执行这段命令就好
